# Generated by Django 4.0.2 on 2022-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=20)),
                ('Taste', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
